### ISSUE TITLE
REQUEST: Federation in Belgium

### ISSUE THREAD

**Issue by PetyaKangalova** [org-id/register#155]
## Request

**What type of organization do you want identifiers for?** Federation

**In which countries are the organizations you want identifiers for based?**:  Belgium

**Do you have examples of organizations you need identifiers for?**

A bit of a background, Belgium NGOs have been mandated to start publishing to IATI next year so I have been supporting them in identifying the correct organisation identifiers. Luckily, all of them are registered with Crossroads Bank for Enterprises that is already on org-id.guide.

The only organisation that is not registered with is FIABEL and I wanted to get your views on whether an alternative list can be identified or we will need to put a proposal for XI-IATI.

FIABEL is a federation of nine institutional actors. They have no website yet and are hosted by another organisation-[ VVOB](http://www.vvob.be/vvob/nl). The institutional actors that are part of the federation will be publishing to IATI, however, FIABEL would also like to separately publish their activities and therefore they need an organisation identifier. I am in touch with Ruth from FIABEL who can provide additional information if needed. She also mentioned that FIABEL were set up when a new legislation was introduced in Belgium back in 2006.

Let me know if you think that there is an identifier they can use or XI-IATI is the only option here.

**Comment by BobHarper1** [comment]
@PetyaKangalova I take it this is not FIABEL listing on the BCE list? (as this organsiation was first registered in 1938...)
http://kbopub.economie.fgov.be/kbopub/toonondernemingps.html?ondernemingsnummer=403009561

To clarify some of the issues here:

- FIABEL is hosted by VVOB - are they a legal entity distinct from VVOB?
- Are FIABEL due to register with CBE in the future? 

Just to get to understand why they are not registered, as my reading of http://www.bridgewest.eu/article/register-non-profit-organization-belgium would interpret that they should be - perhaps our information needs to be updated.

It being the case that there is no registration due to be completed, I think XI-IATI is the only remaining option.

**Comment by PetyaKangalova** [comment]
@BobHarper1 , thanks for the response. I have now received an answer from FIABEL (see below).

> FIABEL is hosted by VVOB – but Fiabel has not a legal entity distinct from VVOB – it is an unincorporated association. We will not register in the crossroad bank for enterprises so it would be great if you can request an xi iati code.

 I will then go ahead with creating an XI-IATI code  and closing the request here.
