### ISSUE TITLE
REQUEST: Organisations in Niger

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#281]
## Request

**What type of organization do you want identifiers for?** 
NGO

**In which countries are the organizations you want identifiers for based?**: 
Niger

**Do you have examples of organizations you need identifiers for?**
Timidria
Registered in Niger with the 'Direction Générale des Impôts' or tax authority. 
Their registration number is 5355.

Registration certificate has been emailed to contact@org-id.guide.

**Comment by kd-ods** [comment]
Research findings to date:

Search by name or Numéro d'Identification Fiscale (NIF) (5355 in this case) does not seem possible at the Direction Générale des Impôts (http://www.impots.gouv.ne/). The page on computerisation at the tax authority - http://www.impots.gouv.ne/informatique - suggests that the NIF may not be reliable as a unique identifier (l’Identifiant Unique).

A Certificat d'Immatriculation has been provided by Timidria on which Timidria provides a 'Numéro du Registre de Commerce' of 159/MI/DAPJ DU 3/12/1991.

It looks like a Directory of Companies might be available via the National Institute of Statistics of Niger (http://www.stat-niger.org/statistique/index.php/bases-de-donnees-2/repertoire-des-entreprises) although it is giving an error message at the moment.

**Comment by kd-ods** [comment]
Hi Jahnvi-

Sorry that I haven't managed to progress this. I need to do a bit more research but I'm likely to suggest that the Direction Générale des Impôts is added to Org-ID so that the Numéro d'Identification Fiscale (NIF) (5355 in this case) can be used. I'll recommend that the list name code be DGI. 

If this is an acceptable addition to the guide then Timidria's identifier would be NE-DGI-5355. I suggest this is used temporarily and I'll progress this when back in the office next week. 

Sorry again for the delay.

**Comment by kd-ods** [comment]
The new list (Direction Générale des Impôts) is now being added to Org-ID so that the Numéro d'Identification Fiscale (NIF) can be used as an organisational identifier. See pull request: https://github.com/org-id/register/pull/291

**Comment by jahnvidave** [comment]
Thank you!!

**Comment by rory09** [comment]
Merged, thanks @kd-ods :)
