### ISSUE TITLE
UK Mutuals register is now open

### ISSUE THREAD

**Issue by drkane** [org-id/register#344]
## Correction

Data is now available in bulk at https://mutuals.fca.org.uk/. Licence is unclear

**Comment by siwhitehouse** [comment]
Thanks @drkane and my apologies for the delay in looking at this.

As I understand it the bulk download is of limited use for creating globally unique ids as you currently still need to go back to the online register in order to verify an organisation's suffix and/or prefix.

It would be possible to create a list with the globally unique ids, by referring to [the glossary](https://mutuals.fca.org.uk/Home/Glossary). But, as you say, the licensing is unclear and so anything created would not be shareable.

**Comment by siwhitehouse** [comment]
An update to the listing has been created and is staged at #345

**Comment by siwhitehouse** [comment]
PR #345 merged into master and the updated list entry is now visible at http://org-id.guide/list/GB-MPR

**Comment by drkane** [comment]
Thanks @siwhitehouse
