### ISSUE TITLE
PROPOSAL: Jersey Charity Register: JE-JCR

### ISSUE THREAD

**Issue by KDuerden** [org-id/register#385]
## Proposal

**The name of the list, or the organization that manages the list**
Jersey Charity Register
Jersey Charity Commissioner: https://charitycommissioner.je/

**A suggested code for the list [optional]**
JE-JCR

**A short description of the list**
The charity register contains key information about each registered charity and, with some limited exceptions, is fully open to public inspection so that people can if they wish understand more about the purposes, finances and public benefit delivery of the charities registered in Jersey.

**The country or countries that the list covers**
Jersey

**The legal form or organizations that the list covers**
Jersey charities including community groups, religious charities, schools, grant-giving charities and major care providers.
Further details about charitable status in Jersey is here: https://charitycommissioner.je/for-the-public/charity-status/

**Any specific sectors that the list covers**
Registered charities

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://portal.charitycommissioner.je/Public-Register/

**Any information on available open data copies of this list**
None found - seems to only be the online search.

**One or more examples of identifier from this list, and how you found them**
Jersey Hospice Care ID 30: https://portal.charitycommissioner.je/Public-Register/View_PublicDetails/?id=d5e0ddf1-96fc-e811-a8a7-002248004c4b (further details accessed by clicking next)
Jersey Cancer Trust ID 45: https://portal.charitycommissioner.je/Public-Register/View_PublicDetails/?id=7c5f2cd1-bb20-e911-a8a6-002248005544

These registered charity numbers are also references in the Association of Jersey Charities member records: 
https://www.jerseycharities.org/members/75/jersey-hospice-care
https://www.jerseycharities.org/members/384/jersey-cancer-trust

**Comment by siwhitehouse** [comment]
Myself and @mrshll1001 reviewed this yesterday. The Jersey Charity Register lists 345 charities registered in Jersey. Their identifiers start from '1' and appear to have been allocated by incrementing.

We are happy that these are unique identifiers.

We had some queries about how stable these identifiers are. The oldest "date of registration" is 12/09/2018 (dd/mm/yyyy) and it is not the case that the oldest charity on Jersey is less than two years old. We have seen the case on other registers where there is an obligation to re-register periodically and that this sometimes results in a change to the identifier iddued by the registrar.

In the case of the JCC, the [Charities (Jersey) Law 2014](https://www.jerseylaw.je/laws/unofficialconsolidated/Pages/15.070.aspx) came into force on 1 May 2018 and it introduced online registration of charities from that date. There is no mention of period re-registration in the law.

It appears that the JCC is probably displaying the date of registration via the online process rather than the initial date of the charity being established. 

It also appears that they probably changed charities unique identifiers in 2018 also. The rationale for this is that charities are often shown as having a legal status of "registered 1868 legislation" (referring to the Loi (1862) sur les teneures en fidéicommis et l’incorporation d’associations) whereas charity #1 was [established in 1959](https://portal.charitycommissioner.je/Public-Register/View_PublicDetails/?id=f040b05f-76b6-e811-a895-002248005489&stepid=256f0d3a-958a-e811-a88e-002248005544&sessionid=cbb38c1b-2389-ea11-a811-000d3a86ad25).

Given this context, the identifiers are "stable enough" for the JCC to be included in org-id as they are unlikely to changed again in the near future.

**Comment by stevieflow** [comment]
Call held 29 April 2020 to check through this.  Agreed to proceed with adding to org-id, @KDuerden will also check directly in terms of uniqueness of IDs, the completeness / timescale of the registrations on the online register (vs actual registration of the entities, which would pre-date the online register).
