### ISSUE TITLE
REQUEST: World Vision DRC

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [org-id/register#401]
## Request

**What type of organization do you want identifiers for?** NGO

**In which countries are the organizations you want identifiers for based?**: DRC

**Do you have examples of organizations you need identifiers for?** World Vision DRC

I have a copy of organisation's certificate of registration with the Ministry of Planning. Please advise on an email address that I would be able to send this to for review.

Thanks,
Josh

**Comment by kd-ods** [comment]
Hello Josh-

We’re on a [hiatus at the moment](http://org-id.guide/about), trying to improve the way that people can contribute to maintenance of, and add new lists to, org-id. During this time, you can use the existing system and resources to submit a pull request to this repository.

The org-id contributors handbook has information to support your [research](http://docs.org-id.guide/en/latest/research/) and to help you [propose a new list entry](http://docs.org-id.guide/en/latest/contribute/#proposing-a-new-entry). If you are familiar with github and json, you can go on to turn this proposal into a pull request.

We realise that this approach is convoluted and tech-heavy, hence our taking a break from doing the research ourselves so that we can improve the contribution process.
