### ISSUE TITLE
PROPOSAL: New List [VAT Number - UE ]

### ISSUE THREAD

**Issue by runobe** [org-id/register#436]
From the City Council of Zaragoza we are working on an API according to the OCDS standard and we need to use a scheme of company identifiers. We propose to use the VAT number of the EU.

## Proposal

**The organization that manages the list**
European Comision

**A short description of the list**
The VAT is an identification code that must be requested by the self-employed and companies that need to carry out commercial operations with other companies in the European Union

**The country or countries that the list covers**
European Union

**The legal form or organizations that the list covers**
The self-employed and companies that need to carry out commercial operations with other companies in the European Union

**Any specific sectors that the list covers**
All sectors

**A URL for information on the list, and a URL for looking up identifiers [if available]**
http://ec.europa.eu/taxation_customs/vies/vieshome.do

**Comment by kd-ods** [comment]
@mrshll1001  - can I assign this to you to look at under an OCDS helpdesk ticket?

(On the content of the proposal: this EU validation service is essentially built to validate nationally-issued VAT numbers. So there will be questions about how/whether to represent this as an org-id entry, since many national VAT schemes in the EU will already exist in org-id.)

**Comment by runobe** [comment]
Hi,
OCDS helpedsk is validating the API of the Zaragoza city council and suggested that we make this request but I do not work or collaborate with them I do not know if this could confuse or disturb.
About of the proposal:
We considered that it was better to have a single European scheme to avoid having to define a scheme for each country.
But if this is not considered an improvement,  we will request the equivalent of the vat Number for Spain: NIF

**Comment by kd-ods** [comment]
@runobe - I have colleagues on the OCDS helpdesk, so this is all as expected :-)

Thanks for the extra info about your implementation.

**Comment by mrshll1001** [comment]
Hi @runobe,

I think that because the VIES system verifies VAT codes and there isn't a central list of codes, this request should be for the NIF. Do you have any links or information about this number to support the research?

**Comment by mrshll1001** [comment]
[ES-NIF](http://org-id.guide/list/ES-NIF) is already listed on Org-id; so if you've got access to the list then I think it's best to use this for now.

**Comment by mrshll1001** [comment]
Closing for the following reasons:

* EU VAT numbers are managed by independent member states, and the VIES doesn't list or republish them but simply verifies that they're in use. It acts as a search engine, rather than a registry or published list ([source](https://ec.europa.eu/taxation_customs/vies/faq.html#item_1)).
* According to [this list](https://en.wikipedia.org/wiki/VAT_identification_number), the identification number to use for Spain is the NIF (CIF)
* We have [ES-NIF](http://org-id.guide/list/ES-NIF) listed on org-id.guide already.

If the EU or VIES ever *republish* a list of identifiers for member states; then we can add this as a secondary list. However the advice for this use-case is to use the NIF.

I will also be contacting Zaragoza via the OCDS Helpdesk to inform them of this from a publisher perspective.

**Comment by runobe** [comment]
Ok , We will use ES-NIF for our Spanish suppliers and we will search for their equivalents for suppliers of other nationalities
