### ISSUE TITLE
PROPOSAL: Catálogo Presupuestario de la Administración Pública Federal de México

### ISSUE THREAD

**Issue by RegulEsteban** [org-id/register#81]
## Proposal

**The name of the list, or the organization that manages the list**
Catálogo Presupuestario de la Administración Pública Federal de México

**A suggested code for the list [optional]**

**A short description of the list**
This list is a scheme for Mexico's administrative classification, which includes the following concepts:
- Ramo: a concept that groups all the specific organizations from Mexico's Public Administration.
- Unidad Responsable: the specific organizations from Mexico's Public Administration

The provided list will always be updated to Mexico's latest fiscal year. 

**The country or countries that the list covers**
Mexico

**The legal form or organizations that the list covers**
Ramo and Unidad Responsable from Mexico's Public Administration 

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers [if available]**
http://www.transparenciapresupuestaria.gob.mx/work/models/PTP/DatosAbiertos/Metadatos/catalogos_presupuestarios.xlsx

**Any information on available open data copies of this list**
http://www.transparenciapresupuestaria.gob.mx/work/models/PTP/DatosAbiertos/Metadatos/catalogos_presupuestarios.xlsx

**One or more examples of identifier from this list, and how you found them**
4 - Gobernación. At the "Ramo" workbook.
5 - Relaciones Exteriores. At the "Ramo" workbook
4 - 100 - Secretaría. At the "Unidad_Responsable" workbook.

**Comment by timgdavies** [comment]
@RegulEsteban Thank you for this research and input. 

A pull request to create this entry with the code MX-CPA is open at #91. 

@RegulEsteban Can you clarify what happens if a government agency was to be closed or merged? Would it's identifier ever be re-assigned to another entity? 

Do identifiers ever change between years?

If there is a webpage that links to the spreadsheet, rather than a direct link to the spreadsheet - I would also prefer to use that in the org-id.guide record.

**Comment by timgdavies** [comment]
This code is now live.
